env:
  browser: true
  commonjs: true
  amd: true
  es6: true
extends: "eslint:recommended"
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2018
rules:
  no-unused-vars:
    - warn
  no-redeclare:
    - off
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - error
  #   - double
  semi:
    - error
    - always
  eol-last:
    - error
    - always
  no-undef:
    - error
    - typeof: true
  no-var:
    - error
